name: maiwayapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

  # UI and Fonts
  cupertino_icons: ^1.0.8

  # Mapping & Location
  flutter_map: ^8.1.1
  flutter_map_location_marker: ^10.0.0
  flutter_map_cancellable_tile_provider: ^3.1.0
  latlong2: ^0.9.1
  google_maps_flutter: ^2.12.2
  geolocator: ^13.0.4
  location: ^8.0.0
  permission_handler: ^12.0.0
  geocoding: ^3.0.0

  # Utilities
  http: ^1.3.0
  intl: ^0.19.0

  # Fonts
  google_fonts: ^6.1.0

  # Firebase
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/gtfs/
    - assets/landmarks.geojson
