name: maiwayapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # Adjusted SDK constraint based on typical latest Flutter compatibility
  # If you're on an older Flutter version, you might need to adjust this back
  # to match your Flutter's Dart SDK version.
  sdk: '>=3.5.0 <4.0.0' # Most packages now require >=3.5.0

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^8.1.1 # Current latest stable
  latlong2: ^0.9.1 # Current latest stable
  flutter_map_location_marker: ^10.1.0 # Current latest stable
  geolocator: ^14.0.1 # Current latest stable
  permission_handler: ^12.0.0+1 # Current latest stable
  location: ^8.0.0 # Current latest stable
  http: ^1.4.0 # Current latest stable
  google_fonts: ^6.2.1 # Current latest stable
  font_awesome_flutter: ^10.8.0 # Current latest stable

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Current latest stable

flutter:
  uses-material-design: true

  # Asset definitions for images, audio, etc.
  assets:
    - assets/maiway_logo.png # Path to your MAIWAY logo image.
    - backend/app.py                         # Ensure this file exists in a folder named 'assets'
    - assets/chatbot_icon.png                         # at the root of your Flutter project.
    # Add other assets here if you have them, e.g.:
    # - assets/some_other_image.png
    # - assets/data.json